<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
    'title.cookie-settings' => 'Cookie-Einstellungen',
    'flash.message.success' => 'Cookie-Einstellungen wurden erfolgreich aktualisiert!',
    'hint.ads' => 'Remarketing-Cookies wie das Remarketing-Cookie von Google AdWords.',
    'hint.behavior' => 'Cookies zum Speichern benutzerbezogenen Verhaltens. Wie diese Einstellung in dieser Form.',
    'hint.social' => 'Cookies, die von Social-Network-Widgets wie dem Facebook-Plugin oder Google Maps verwendet werden',
    'hint.statistics' => 'Cookies, mit denen wir die Leistung dieser Website messen können. Zum Beispiel das Verfolgen von Conversions in Google Analytics und Facebook.',
    'hint.session' => 'Sitzungs-Cookies sind erforderlich, um Benutzer auf der Site zu unterscheiden',
    'hint.usage_helper' => 'Cookies zum Speichern von Informationen wie dem Kontrollkästchen "Erinnere dich an mich" in Anmeldeformularen.',
    'input.allowed' => 'On',
    'input.disallowed' => 'Off',
    'label.ads' => 'Ad cookies',
    'label.behavior' => 'Verhaltenscookies',
    'label.statistics' => 'Statistik-Cookies',
    'label.session' => 'Sitzungscookies',
    'label.social' => 'Cookies für soziale Netzwerke',
    'label.usage_helper' => 'Verwendung von Hilfskeksen',
    'btn.save' => 'Speichern',
    'btn.reset' => 'Zurücksetzen'
);
